stages:
- "test"

.test-template:
  stage: test
  image: python:3.9.6-slim-buster
  tags:
  - kubernetes-runner
  - docker-runner
  except:
  - tags
  before_script:
  - pip install poetry==1.1.7
  - poetry config virtualenvs.create false
  - poetry install

black:
  extends:
  - .test-template
  script:
  - black --check .

mypy:
  extends:
  - .test-template
  script:
  - mypy .

pytest:
  extends:
  - .test-template
  script:
  - pytest -vv --cov="eager_cache" .
