@startuml
title eager_cache
scale max 1000*1000
skinparam Padding 10

cloud "A" {
  [Data Source A]
  database {
    [Resource A]
    [Resource B]
  }
}

cloud "B" {
  [Data Source B]
  database {
    [Resource A] as [Resource BA]
    [Resource B] as [Resource BB]
  }
}

cloud {
  [Consumer]
}

cloud {
  [eager_cache]
}

cloud {
  [updater]
}

database "Redis" {
  folder "Cache" {
    [A] as [A Cache]
    [B] as [B Cache]
  }
}

[Consumer] --> [eager_cache]

[eager_cache] --> [Data Source A]
[eager_cache] --> [Data Source B]
[eager_cache] --> [A Cache]

[A Cache] .up.> [updater] : psubscribe to\nkeyspace events
[updater] .left.> [eager_cache] : update on keyspace events

@enduml
