version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: eager_cache:${EAGER_CACHE_VERSION:-latest}
    restart: always
    env_file:
    - .env
    depends_on:
      redis:
        condition: service_healthy
    environment:
      EAGER_CACHE_HOST: 0.0.0.0

  updater:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    command: ["/usr/local/bin/python", "eager_cache/updater.py"]
    image: eager_cache:${EAGER_CACHE_VERSION:-latest}
    restart: always
    env_file:
    - .env
    depends_on:
      api:
        condition: service_healthy
    environment:
      EAGER_CACHE_HOST: 0.0.0.0

  redis:
    image: bitnami/redis:6.2.5
    hostname: eager_cache-redis
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 1s
      timeout: 3s
      retries: 30
